apiVersion: v1
kind: Service
metadata:
  name: esther-image-service
  namespace: esther-ns
spec:
  type: NodePort
  selector:
    app: python
    name: esther-app
  ports:
    - port: 8080
     
      targetPort: 8080
      nodePort: 31313
